name: mvn + docker
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          R2DBC_LOG_LEVEL=DEBUG
          DOMAIN_LOG_LEVEL=DEBUG
          WEB_LOG_LEVEL=DEBUG
          PG_HOST=localhost
          PG_USERNAME=user
          PG_PASSWORD=password
          mvn clean install
      - name: Build and Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: abialiauski/weeks
          tags: 0.0.$GITHUB_RUN_NUMBER, latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}