name: PR CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          R2DBC_LOG_LEVEL=DEBUG
          DOMAIN_LOG_LEVEL=DEBUG
          WEB_LOG_LEVEL=DEBUG
          PG_HOST=localhost
          PG_USERNAME=user
          PG_PASSWORD=password
          mvn clean install